AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description:
  The barebone for aws lambda using koa and api gateway
Globals:
  Function:
    Timeout: 30
    Runtime: nodejs10.x
    MemorySize: 512
Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: API
      StageName: Test
      Cors:
        AllowMethods: "'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
  APIRoutes:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: "./src"
      Handler: index.handler
      Events:
        APIEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /{proxy+}
            Method: ANY
